# Generated by Django 4.1.3 on 2022-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='C:/Users/revel/Desktop/Phyton_git/studbud/studbud/base/static/images/avatar.svg', null=True, upload_to=''),
        ),
    ]
